<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <link href="/bootstrap-datetimepicker/sample in bootstrap v3/bootstrap/css/bootstrap.min.css" rel="stylesheet" media="screen">
    <link href="/bootstrap-datetimepicker/css/bootstrap-datetimepicker.min.css" rel="stylesheet" media="screen">
</head>
<body>
<? include 'menu.phtml'; ?>
<div class="container">
    <? include $defaultTemplatePath; ?>
</div>
<script type="text/javascript" src="/bootstrap-datetimepicker/sample in bootstrap v3/jquery/jquery-1.8.3.min.js" charset="UTF-8"></script>
<script type="text/javascript" src="/bootstrap-datetimepicker/sample in bootstrap v3/bootstrap/js/bootstrap.min.js"></script>
<script type="text/javascript" src="/bootstrap-datetimepicker/js/bootstrap-datetimepicker.js" charset="UTF-8"></script>
<script type="text/javascript" src="/bootstrap-datetimepicker/js/locales/bootstrap-datetimepicker.ru.js"
        charset="UTF-8"></script>
<script type="text/javascript">
    $('#datetime').datetimepicker({
        language: 'ru',
        format: 'yyyy-mm-dd hh:mm:ss'
    });
</script>
</body>
